name: caretime
description: "CareTime is a complete medical appointment management application, designed to facilitate appointment booking between patients, doctors."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/caretime_2x1.png
    - assets/images/caretime_100x100_nobg.png
    - assets/images/Logo-caretime.png
    - assets/images/male-doctor-icon.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/caretime_100x100_nob.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Logo-caretime.png
  android: true
  ios: true
  web: false